##################################################################################
# Data Visualization
# With ever increasing volume of data, it is impossible to tell stories without 
# visualizations. Data visualization is another great tool to how to turn numbers
# into useful knowledge.
# Selecting the Right Chart Type. There are four basic presentation types:
# 1) Comparison
# 2) Composition
# 3) Distribution
# 4) Relationship
# 
# 1. Basic Plots
# 2. Lattice Package
# 3. ggplot2 Package
##################################################################################

###################
# 1. Basic Plots
###################

# We will use the dataset called the air quality dataset, which pertains to the 
# daily air quality measurements in New York from May to September 1973. 
# This dataset consists of more than 100 observations on 6 variables 
# i.e. Ozone(mean parts per billion), Solar.R(Solar Radiation), Wind(Average wind speed), 
# Temp(maximum daily temperature in Fahrenheit), Month(month of observation),
# and Day(Day of the month)
# To load the built-in dataset into the R type the following command in the console:

data(airquality)

# Data Exploration - it is time to explore it to get an idea about its structure.

str(airquality)     # Displays the data structure and overview of the rows and columns of the dataset.
head(airquality,5) 
tail(airquality,5)   
summary(airquality) # The summary method displays descriptive statistics for every variable

# Getting Started with Basic Plots
# The graphics package is used for plotting base graphs like scatter plot, 
# box plot etc. A complete list of functions with help pages: 
library(help = "graphics")

# 1) Scatter Plot

# The plot() function is a kind of a generic function for plotting of R objects.
plot(airquality$Ozone)

# We get a scatter/dot plot here wherein each dot represents the value of the Ozone in mean 
# parts per billion.

# Let us now plot a graph between the Ozone and Wind values to study the relationship between the two.

plot(airquality$Ozone, airquality$Wind)

# The plot shows that Wind and Ozone values have a somewhat negative correlation.

# What happens when we use plot command with the entire dataset without selecting any 
# particular columns?

plot(airquality)
plot(iris)
str(iris)

# We get a matrix of scatterplots which is a correlation matrix of all the columns. 
# The plot above instantly shows that:
# - The level of Ozone and Temperature is correlated positively.
# - Wind speed is negatively correlated to both Temperature and Ozone level.
# We can quickly discover the relationship between variables by merely looking at 
# the plots drawn between them.

# Using arguments with the plot() function: We can easily style our charts by 
# playing with the arguments of the plot() function.

# type argument: The plot function has an argument called type which can take in values like 
# p: points, l: lines,b: both etc. This decides the shape of the output graph.

# points and lines 
plot(airquality$Ozone, type= "p")

# high density vertical lines.
plot(airquality$Ozone, type= "h")
plot(airquality$Ozone, type= "l")
plot(airquality$Ozone, type= "b")

# You can read more about the plot() command by typing ?plot() in the console.
?plot()

# Labels and Titles: We can also label the X and the Y axis and give a title to our plot. 
# Additionally, we also have the option of giving color to the plot.

plot(airquality$Ozone, airquality$Wind, 
     xlab = 'ozone Concentration', ylab = 'No of Instances', 
     main = 'Ozone levels in NY city', 
     col = 'red')

# 2) Barplot - data is represented in the form of rectangular bars and the length of 
# the bar is proportional to the value of the variable or column in the dataset. 
# Both horizontal, as well as a vertical bar chart, can be generated by tweaking the
# horiz parameter.

# Horizontal bar plot
barplot(airquality$Ozone, 
        main = 'Ozone Concenteration in air',
        xlab = 'ozone levels', 
        col= 'green',horiz = TRUE)

# Vertical bar plot
barplot(airquality$Ozone, 
        main = 'Ozone Concenteration in air',
        xlab = 'ozone levels', 
        col='red',horiz = FALSE)

# 3) Histogram is quite similar to a bar chart except that it groups values into continuous ranges. 
# A histogram represents the frequencies of values of a variable bucketed into ranges.

hist(airquality$Solar.R)

# We get a histogram of the Solar.R values. By giving an appropriate value for the 
# color argument, we can obtain a coloured histogram as well.

hist(airquality$Solar.R, 
     main = 'Solar Radiation values in air',xlab = 'Solar rad.', 
     col='purple')

# 4) Boxplot: We have seen how the summary() command in R can display the descriptive 
# statistics for every variable in the dataset. Boxplot does the same graphically 
# in the form of quartiles. It is again very straightforward to plot a boxplot in R.

#Single box plot
boxplot(airquality$Solar.R, main='Single Boxplot')

# Multiple box plots
boxplot(airquality[,0:4], main='Multiple Boxplots')

str(airquality)


# 5) Grid of Charts: There is a very interesting feature in R which enables us to 
# plot multiple charts at once. This comes in very handy during the EDA since the 
# need to plot multiple graphs one by one is eliminated.

# For drawing a grid, the first argument should specify certain attributes like 
# the margin of the grid(mar), no of rows and columns(mfrow), whether a border is 
# to be included(bty) and position of the labels
# (las: 1 for horizontal, las: 0 for vertical).

?par()

par(mfrow=c(3,3), mar=c(2,5,2,1), las=1, bty="n")
plot(airquality$Ozone)
plot(airquality$Ozone, airquality$Wind)
plot(airquality$Ozone, type= "c")
plot(airquality$Ozone, type= "s")
plot(airquality$Ozone, type= "h")
barplot(airquality$Ozone, 
        main = 'Ozone Concenteration in air',
        xlab = 'ozone levels', col='green',horiz = TRUE)
hist(airquality$Solar.R)
boxplot(airquality$Solar.R)
boxplot(airquality[,0:4], main='Multiple Box plots')

#######################################################################################
# Visualisation libraries in R
# R comes equipped with sophisticated visualisation libraries having great capabilities
# Let us have a closer look at some of the commonly used ones. We will
# use the built-in mtcars dataset to show the uses of the various libraries. This 
# dataset has been extracted from the 1974 Motor Trend US magazine.
#######################################################################################

######################
# 2. Lattice Package
######################
str(iris)
# Lattice package is essentially an improvement upon the R Graphics package and is used
# to visualize multivariate data. Lattice enables the use of trellis graphs. 
# Trellis graphs exhibit the relationship between variables which are dependent on one or more 
# variables.  
# It is very straightforward to use the lattice library. 
# One simply needs to plug in the columns for which the plot is desired.

# Installing & Loading the package
install.packages("lattice")
library(lattice)  #Loading the dataset
attach(mtcars)
detach(mtcars)
# Exploring the dataset
head(mtcars)
# Before proceeding with the working of the lattice package, let us do a little 
# pre-processing of the data. There are two columns in our mtcars dataset namely 
# gear and cyl which are categorical in nature. We need to factorize them to make 
# them more meaningful.


gear_factor<-factor(gear,levels=c(3,4,5),
                    labels=c("3gears","4gears","5gears")) 

cyl_factor <-factor(cyl,levels=c(4,6,8),
                    labels=c("4cyl","6cyl","8cyl"))
detach(mtcars)
# Now let us see how we can use the lattice package to create some basic plots in R.

# Kernel density plots

densityplot(~mpg, main="Density Plot",  xlab="Miles per Gallon")

# scatterplot matrix

splom(mtcars[c(1,3,4)], main="MTCARS Data")

?splom

#####################
# 3. ggplot2 Package
#####################

# The ggplot2 package is one of the most widely used visualisation packages in R. 
# It enables the users to create sophisticated visualisations with little code using
# the Grammar of Graphics. 

# The Grammar of Graphics is a general scheme for data visualization which breaks up 
# graphs into semantic components such as scales and layers.

# The popularity of ggplot2 has increased tremendously in recent years since it makes
# it possible to create graphs that contain both univariate and multivariate data in 
# a very simple manner.

# A quick overview of ggplot2
# ggplot2 has several advantages:
# - Plot specification at a high level of abstraction
# - Very flexible
# - Theme system for polishing plot appearance
# - Mature and complete graphics system
# - Many users, active mailing list
# - Lot's of online help available (StackOverflow, etc...)

# What ggplot2 not ideal for:
# - Interactive graphics
# - Graph Theory Plots (Graph Nodes)
# - 3-D Graphics

#Installing & Loading the package 

#install.packages('ggplot2') 
library(ggplot2)
detach(mtcars)
#Loading the dataset
attach(mtcars)
# create factors with value labels 
head(mtcars)
unique(gear)
levels(gear)

mtcars$gear <- factor(mtcars$gear,levels=c(3,4,5),  
                      labels=c("3gears", "4gears", "5gears")) 


unique(am)

mtcars$am <- factor(mtcars$am,levels=c(0,1),  
                    labels=c("Automatic","Manual"))  

unique(cyl)
mtcars$cyl <- factor(mtcars$cyl,levels=c(4,6,8),  
                     labels=c("4cyl","6cyl","8cyl"))

# Let us create a few plots to understand the capability of ggplot2

## Scatter Plots
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg))
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) + geom_point()

# geom_point() is used to create scatterplots and geom can have 
# many variations like geom_jitter(), geom_count(), etc
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) + geom_jitter()

ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) + geom_count()
?ggplot
?geom_jitter()
?geom_count()

# Styling scatter plots by factor
# We know that the dataset mtcars consists of certain variables which are in the 
# form of factors. We can utilise this property to split our dataset
palette()
cc <- palette()
palette(c(cc,"purple","brown"))
palette()
palette("default")

cyl <- factor(cyl,levels=c(4,6,8),  
              labels=c("4cyl","6cyl","8cyl"))
source("code_that_generates_data_for_ggplot.R", encoding="UTF-8")
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg, color = am)) + geom_point()


ggplot(iris, aes(x=Sepal.Length, y=Petal.Length, color=Species)) + geom_point()

# The color parameter is used to differentiate between different factor level of 
# the cyl variable.

# Styling scatter plots by size

# Another useful feature of ggplot2 is that it can be styled according to the 
# size of the attributes.

ggplot(data = mtcars, mapping = aes(x = wt, y = mpg, size = qsec)) + geom_point()

# In the above example, the value of qsec indicates the acceleration which 
# decides the size of the points

# Different symbols for different sizes: With ggplot2, one can also create unique and
# interesting shapes by layering multiple points of different sizes
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg,color=am)) + geom_point()+
      facet_grid(am ~ .)   # allow put multiple plots in a single canvas


###################################################################################
# Visualizing Geographical data in R
# Geographic data (Geo data) relates to the location-based data. It primarily deals
# with describing objects with respect to their relationship in space. The data is 
# usually stored in the form of coordinates. It makes more sense to be able to see
# a state or a country in the form of a map as it gives a more realistic overview. 
# In the section below, we will briefly outline the capabilities of R in terms of 
# geographical data visualisation.
###################################################################################

# Geographical maps: We will be working with a sample superstore dataset of the ABC 
# company. The dataset consists of locations of their stores in the US. Let’s load 
# in the data and check out its columns.
getwd()
setwd("C:\\Users\\chris\\OneDrive\\Desktop\\TeachingUChicago\\Autumn2020\\Data")
library(readr)
ABC <- read.csv('ABCLocationsNew.csv')
head(ABC)

# plot() function: We will create a crude map by simply the Latitude and 
# the Longitude column.

# To reset your graphics device, call the following code from the console:
dev.off()

plot(ABC$Longitude,ABC$Latitude)

# The output isn’t an exact map but it does give a faint outline of the US boundary.
# map() function

# maps package is very useful and pretty straightforward when it comes to plotting 
# the geographical data.
install.packages('maps', dependencies=TRUE)
library(maps)

#Using the map() function to plot a base map of the US
map(database="state")

# Building a point map on top of the base map using symbols() function
symbols(ABC$Longitude, ABC$Latitude, squares =rep(1, length(ABC$Longitude)), 
        inches=0.03, add=TRUE)

# Giving the symbols a color
symbols(ABC$Longitude, ABC$Latitude,bg = 'red', fg = 'red', 
        squares =rep(1, length(ABC$Longitude)), inches=0.03, add=TRUE)
?symbols()


